### ISSUE TITLE
Using a different  enum representation breaks things

### ISSUE THREAD

**Issue by DevasiaThomas** [minghuaw/toy-rpc#32]
Hi @minghuaw :)

Using the Consumer service in the examples, if I try to send an enum that looks like this

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Message {
    New(SomeStructA),
    Old(SomeStructB),
}
```
things are fine, but as soon as I add/remove tagging to the enum as described [here](https://serde.rs/enum-representations.html), it fails to work.. I can't tell if the connection dropped or some parsing error happened. it's very silent. 

The reason I am using tagging is because downstream I have to serialize to json(and java libraries don't know what externally tagged representations are - I have to create container classes :D) and I don't really want to maintain different versions of the protocol tbh.

**Comment by minghuaw** [comment]
I will look into it

**Comment by minghuaw** [comment]
I think I have found the problem, assuming that you were using the `bincode` binary encoding (which is the default one). There's good news and bad news. 

The bad news is that the problem, unfortunately, is caused by `bincode` not supporting tagging with `#[serde(tag = "type")]` macro (the issue can be found [here](https://github.com/bincode-org/bincode/issues/272)). 

However, the good news is that if you change the encoding to json and disable the default bincode format, you will get this functionality. The change is really simple, in all of your crates that uses `toy-rpc`, make sure to disable the default features (actually the only default feature is `"serde_bincode"`) and add `"serde_json"` to the list of features. Below are some examples

[example-service](https://github.com/minghuaw/toy-rpc/blob/0.9-devel/examples/example-service/Cargo.toml)

```toml
[dependencies.toy-rpc]
version = "0.8.4"
default-features = false # Make sure default feature is disabled everywhere
```

[example-server](https://github.com/minghuaw/toy-rpc/blob/0.9-devel/examples/example-server/Cargo.toml)

```toml
[dependencies.toy-rpc]
version = "0.8.4"
default-features = false # Make sure default feature is disabled everywhere
features = [ "serde_json", "tokio_runtime", "server", "anyhow" ] # Add "serde_json" to features
```

[example-client](https://github.com/minghuaw/toy-rpc/blob/0.9-devel/examples/example-client/Cargo.toml)

```toml
[dependencies.toy-rpc]
version = "0.8.4"
default-features = false # Make sure default feature is disabled everywhere
features = [ "serde_json", "tokio_runtime", "client"] # Add "serde_json" to features
```
